### ISSUE TITLE
Implement jwt token

### ISSUE THREAD

**Issue by BTopchiyski** [BTopchiyski/SoftwareTechnologies#18]

**Comment by BTopchiyski** [comment]
Fix issue: 
class org.springframework.security.core.userdetails.User cannot be cast to class bg.healthcheck.BIYD.services.CustomUserDetails (org.springframework.security.core.userdetails.User and bg.healthcheck.BIYD.services.CustomUserDetails are in unnamed module of loader 'app')
	at bg.healthcheck.BIYD.security.JWT.JwtUtils.generateJwtToken(JwtUtils.java:24) ~[classes/:na]
	at bg.healthcheck.BIYD.controllers.AuthController.authenticateUser(AuthController.java:53) ~[classes/:na]
